# Stage 1: Build Angular app
FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build --configuration production

# Stage 2: Serve với Nginx
FROM nginx:alpine
COPY --from=build /app/dist/* /usr/share/nginx/html
EXPOSE 80

# Tùy chỉnh config Nginx để Angular xử lý route
COPY nginx.conf /etc/nginx/conf.d/default.conf
