services:
  discovery:
    build:
      context: .
      dockerfile: discovery/Dockerfile
    volumes:
      - ${USERPROFILE}\.m2:/root/.m2

    container_name: discovery-service
    ports:
      - "8761:8761"
    restart: always

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"
    restart: always


  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    container_name: auth-service
    ports:
      - "8081:8081"
    restart: always
#    networks:
#      - auth

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    container_name: product-service
    ports:
      - "8082:8082"
    restart: always
#    networks:
#      - product-service

  cart-service:
    build:
      context: .
      dockerfile: cart-service/Dockerfile
    container_name: cart-service
    ports:
      - "8083:8083"
    restart: always
#    networks:
#      - cart-service

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    ports:
      - "8084:8084"
    restart: always
#    networks:
#      - order-service
